name: Build README

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 7-23/2 * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout project source code
      - uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Use NodeJs 20.x
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install npm dependencies
      - name: Install dependencies
        run: npm install

      # Generate updated README file
      - name: Generate updated README file
        run: npm start
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}

      # Commit and push new README.md to the repository
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}