name: Metrics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create assets directory
        run: mkdir -p assets

      - name: Generate isocalendar metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: "UTC"
          filename: assets/isocalendar-metrics.svg

      - name: Generate WakaTime metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, projects, languages, editors, os, categories, projects-graphs, languages-graphs,editors-graphs
          plugin_wakatime_days: 365
          filename: assets/metrics.plugin.wakatime.svg

      - name: Generate repository metrics for ottos-bible
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          template: repository
          user: ottojonas
          repo: ottos-bible
          plugin_lines: yes
          plugin_followup: yes
          filename: assets/metrics.ottos-bible.svg

      - name: Generate repository metrics for config-and-equipment
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          template: repository
          user: ottojonas
          repo: config-and-equipment
          plugin_lines: yes
          plugin_followup: yes
          filename: assets/metrics.config-and-equipment.svg

      - name: Generate repository metrics for peacockgpt
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          template: repository
          user: ottojonas
          repo: peacockgpt
          plugin_lines: yes
          plugin_followup: yes
          filename: assets/metrics.peacockgpt.svg

      - name: Generate repository metrics for jeaneth-app
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          template: repository
          user: ottojonas
          repo: jeaneth-app
          plugin_lines: yes
          plugin_followup: yes
          filename: assets/metrics.jeaneth-app.svg

      - name: Generate repository metrics for scribe
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: repository
          user: ottojonas
          repo: Scribe
          plugin_lines: yes
          plugin_followup: yes
          filename: assets/metrics.scribe.svg

      - name: Generate repository metrics for copilotprototypedemo
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: repository
          user: ottojonas
          repo: CopilotPrototypeDemo
          plugin_lines: yes
          plugin_followup: yes
          filename: assets/metrics.copilotprototypedemo.svg

      - name: Generate repository metrics for visualstudioplugin
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: repository
          user: ottojonas
          repo: git-status-checker-vsc-plugin
          plugin_lines: yes
          plugin_followup: yes
          filename: assets/metrics.visualstudioplugin.svg

      - name: Check if repository metrics file exists
        id: check_file
        run: |
          if [ -f assets/metrics.ottos-bible.svg ]; then
            echo "File exists"
            echo "::set-output name=file_exists::true"
          else
            echo "File does not exist"
            echo "::set-output name=file_exists::false"
          fi

      - name: Set up Git
        run: |
          git config --global user.name 'ottojonas'
          git config --global user.email 'ottobjonas@outlook.com'

      - name: Check for changes
        id: changes
        run: |
          git add .
          if [ "${{ steps.check_file.outputs.file_exists }}" == "true" ]; then
            git add assets/metrics.ottos-bible.svg
          fi
          git add assets/metrics.config-and-equipment.svg
          if git diff-index --quiet HEAD; then
            echo "No changes detected"
            echo "::set-output name=changes_detected::false"
          else
            echo "Changes detected"
            echo "::set-output name=changes_detected::true"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changes_detected == 'true'
        run: |
          git commit -m 'Update GitHub metrics'
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
