name: Update Stats

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Make fetch_stats.sh executable
        run: chmod +x fetch_stats.sh

      - name: Run fetch_stats.sh
        run: ./fetch_stats.sh

      - name: Check for changes
        id: changes
        run: |
          git add assets/stats.svg assets/languages.svg assets/ottosbible.svg
          if git diff-index --quiet HEAD; then
            echo "No changes detected"
            echo "::set-output name=changes_detected::false"
          else
            echo "Changes detected"
            echo "::set-output name=changes_detected::true"
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changes_detected == 'true'
        run: |
          git commit -m 'update stats and languages'
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
