name: Update Stats

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Make fetch_stats.sh executable
        run: chmod +x fetch_stats.sh

      - name: Run fetch_stats.sh
        run: ./fetch_stats.sh

      - name: Commit and push changes
        run: |
          git add . 
          git commit -m 'update stats and languages'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
