name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # content
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ░▒▓█
          CODE_LANG: rust
          TIME_RANGE: all_time
          LANG_COUNT: 4
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: YAML JSON TOML
          # commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: ottojonas
          AUTHOR_EMAIL: ottobjonas@outlook.com
